// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcgKvhbieWjOwegK2Zk2ml2dCA1B5m7TI',
    appId: '1:166346949750:web:dde1d5f27068ffc553cb57',
    messagingSenderId: '166346949750',
    projectId: 'mova-4edc6',
    authDomain: 'mova-4edc6.firebaseapp.com',
    storageBucket: 'mova-4edc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnt5rn-Qd3zUYEkV0kdoaPPvW8ZIb6auI',
    appId: '1:166346949750:android:4a92d108850b49de53cb57',
    messagingSenderId: '166346949750',
    projectId: 'mova-4edc6',
    storageBucket: 'mova-4edc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvFj-ZbZLvQGGgfVVnFVJ1O2JJlYpVlzI',
    appId: '1:166346949750:ios:edcc42ff168f23a453cb57',
    messagingSenderId: '166346949750',
    projectId: 'mova-4edc6',
    storageBucket: 'mova-4edc6.appspot.com',
    iosClientId: '166346949750-nq45n03nej87o2pujqcevgsv7dknbe61.apps.googleusercontent.com',
    iosBundleId: 'com.example.movaContentMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvFj-ZbZLvQGGgfVVnFVJ1O2JJlYpVlzI',
    appId: '1:166346949750:ios:edcc42ff168f23a453cb57',
    messagingSenderId: '166346949750',
    projectId: 'mova-4edc6',
    storageBucket: 'mova-4edc6.appspot.com',
    iosClientId: '166346949750-nq45n03nej87o2pujqcevgsv7dknbe61.apps.googleusercontent.com',
    iosBundleId: 'com.example.movaContentMaker',
  );
}
